# Generated by Django 4.2.20 on 2025-04-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code, e.g., 'M', 'F', 'MN', 'FS'", max_length=10, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Sex',
                'verbose_name_plural': 'Sexes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code, e.g., 'canine', 'feline'", max_length=50, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['owner__last_name', 'name'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years', null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (e.g., in kg)', max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code for the breed, e.g., 'golden_retriever'", max_length=100, unique=True, verbose_name='Code')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='main.species')),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'ordering': ['species', 'code'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='main.sex', verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='main.breed', verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='main.species', verbose_name='Species'),
        ),
        migrations.CreateModel(
            name='SpeciesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('el', 'Greek')], max_length=10, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.species')),
            ],
            options={
                'verbose_name': 'Species Translation',
                'verbose_name_plural': 'Species Translations',
                'ordering': ['language', 'name'],
                'unique_together': {('species', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SexTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('el', 'Greek')], max_length=10, verbose_name='Language')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.sex')),
            ],
            options={
                'verbose_name': 'Sex Translation',
                'verbose_name_plural': 'Sex Translations',
                'ordering': ['language', 'name'],
                'unique_together': {('sex', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BreedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('el', 'Greek')], max_length=10, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.breed')),
            ],
            options={
                'verbose_name': 'Breed Translation',
                'verbose_name_plural': 'Breed Translations',
                'ordering': ['language', 'name'],
                'unique_together': {('breed', 'language')},
            },
        ),
    ]
